#!/usr/bin/env bash
#Print each of these numbers and their square roots
num1=$RANDOM
num2=$RANDOM

# getting the square roots 
sqrt_num1=`echo "sqrt($num1)" | bc`
sqrt_num2=`echo "sqrt($num2)" | bc`

# get the sum of squares 
addition=$(($sqrt_num1+$sqrt_num2))
# printing out the values 
echo "The first random number generated is $num1"
echo "The square root is $sqrt_num1"
echo "The first random number generated is $num2"
echo "The square root is $sqrt_num2"
echo "The sum of their square roots is $addition"
